version: '3'
services:
  php-apache:
    container_name: php-apache
    build: apache-php
    volumes:
      - ./apache-php/src:/var/www/html-dynamic
    ports:
      - 8081:8081
  nginx:
    container_name: nginx
    build: nginx
    volumes:
      - ./nginx/src:/usr/share/nginx/html-static
    ports:
      - 8082:8082
  db:
    image: mysql
    command: --init-file /data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: appDb
      MYSQL_USER: user
      MYSQL_PASSWORD: example
    volumes:
      - ./db/init.sql:/data/application/init.sql
  adminer:
    image: adminer
    restart: always
    ports:
     - 8080:8080